<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
 <Actions category="Scripts">
        <text>Split the text</text>

          <Action name="split_text">
            <text>Split multiple line text with line break.</text>
            <shortcut>none</shortcut>
            <isCheckable>false</isCheckable>
          </Action>

</Actions>
</ActionCollection>